In [1]:
import numpy as np

In [2]:
dt = 5.0 # Delta t em segundos
z_0 = np.array([[10000.0],
                [200.0]]) # Medição inicial [Alcance, Velocidade]

sigma_r = 4.0 # Desvio padrão do alcance
sigma_v = 0.5 # Desvio padrão da velocidade
sigma_a = 0.2 # Desvio padrão da aceleração aleatória (ruído do processo)

In [3]:
# A estimativa inicial é igual à primeira medição
x_0_0 = z_0

# A matriz de covariância inicial P é igual à matriz de incerteza da medição R
R_0 = np.array([[sigma_r**2, 0],
                [0, sigma_v**2]])
P_0_0 = R_0

print("Estado Inicial (x_0_0):")
print(x_0_0)
print("\nCovariância Inicial (P_0_0):")
print(P_0_0)

Estado Inicial (x_0_0):
[[10000.]
 [  200.]]

Covariância Inicial (P_0_0):
[[16.    0.  ]
 [ 0.    0.25]]


In [4]:
# Matriz de Transição de Estado (F)
F = np.array([[1.0, dt],
              [0.0, 1.0]])

# Matriz de Ruído do Processo (Q)
var_a = sigma_a**2
Q = np.array([[(dt**4)/4, (dt**3)/2],
              [(dt**3)/2, dt**2]]) * var_a

print("Matriz de Transição de Estado (F):")
print(F)
print("\nMatriz de Ruído do Processo (Q):")
print(Q)

Matriz de Transição de Estado (F):
[[1. 5.]
 [0. 1.]]

Matriz de Ruído do Processo (Q):
[[6.25 2.5 ]
 [2.5  1.  ]]


In [5]:
# 1. Extrapolação do Estado: x_1_0 = F * x_0_0
x_1_0 = np.dot(F, x_0_0)

# 2. Extrapolação da Covariância: P_1_0 = F * P_0_0 * F^T + Q
P_1_0 = np.dot(np.dot(F, P_0_0), F.T) + Q

print("ESTADO PREVISTO PARA t1 (x_1_0):")
print(x_1_0)
print("\nCOVARIÂNCIA PREVISTA PARA t1 (P_1_0):")
print(P_1_0)

ESTADO PREVISTO PARA t1 (x_1_0):
[[11000.]
 [  200.]]

COVARIÂNCIA PREVISTA PARA t1 (P_1_0):
[[28.5   3.75]
 [ 3.75  1.25]]
